import Phaser from "phaser";
import type { PublicContestant } from "@arena/shared";
import {
  createCameraController,
  type CameraControllerHandle,
  type CameraFollowTarget,
} from "../cameraController";
import { buildTagPill } from "../tagPill";
import { forget, RENDER_DELAY_MS, samplePosition } from "../interpolation";
import { onFight } from "../combatEvents";
import {
  normalizedWinProbs,
  selectMyContestantId,
  selectMyPositions,
  useGameStore,
  type ClientConversation,
  type GameStore,
} from "@/lib/gameStore";
import { islandFlags } from "@/lib/islandFlags";
import { isNotableOutcome, outcomePresentation } from "@/lib/outcomes";

type TreePlacement = { x: number; y: number; variant: number };
type LandmarkPlacement = {
  x: number;
  y: number;
  kind: "villa" | "pond" | "garden" | "shrine" | "dock";
};

type IslandMapData = {
  tileSize: number;
  width: number;
  height: number;
  ground: number[][];
  decor: number[][];
  walkable: boolean[][];
  trees: TreePlacement[];
  landmarks: LandmarkPlacement[];
};

// Tile indices, mirroring apps/web/scripts/generate-assets.mjs (TILE_INDEX).
// Packed sheet is 8 columns wide; index = row * 8 + col. Trees are no longer
// a tilemap tile -- they're big, non-16px-grid canopies rendered as separate
// Image objects from map.trees (see placeTrees), so only the small ground
// clutter still lives in the tilemap's decor layer.
const ROCK = 18; // row 2, col 2
const BUSH = 17; // row 2, col 1
const FLOWER_A = 19; // row 2, col 3
const FLOWER_B = 20; // row 2, col 4
const FLOWER_C = 21; // row 2, col 5
const BLANK = 6; // row 0, col 6 -- reserved fully-transparent cell, safe "no decoration" sentinel

// Depth ladder: decorLow(1) < decorHigh/rock(1.6) < trees(1.8) < the y-sorted
// contestant/structure band(2+) < conv nodes(5) < voice icons/fight spark(6).
// Trees and small scenery stay below every contestant, keeping the roster
// readable even beneath broad canopies. Only the solid villa/shrine/garden use
// positional occlusion, and the server prevents sprites entering their bases.
const TREE_DEPTH = 1.8;

// Tree PNG variants generated by scripts/generate-assets.mjs (TREE_VARIANTS):
// tree0 green tree, tree1 fruit tree, tree2 bush. map.trees[].variant indexes
// into this set; anything out of range falls back to tree0.
const TREE_TEXTURE_COUNT = 3;
const LANDMARK_KINDS = ["villa", "pond", "garden", "shrine", "dock"] as const;
const WATER_TILE_INDICES = new Set([3, 7, 16]);
const BEACH_TILE_INDICES = new Set([4, 5, 29, 30, 31, 37, 38, 39, 45, 46]);

// Screen-space width the desktop activity-feed rail occupies on the right
// (w-80 = 320px + 16px right margin). The camera keeps the island centered in
// the area left of it; keep in sync with src/app/page.tsx.
const FEED_PANEL_INSET = 336;

// The other two pieces of opaque chrome the camera has to frame around while
// following. Neither is modeled at the fit rung (the fit view has always
// ignored them), but both matter the moment a follow starts: the Follow
// control lives in the ContestantPanel, so THAT panel is open for the whole
// time a follow is active, and the ConversationPanel is exactly what a viewer
// opens to read the conversation they are watching. Same "documented constant
// kept in sync with the component" idiom as FEED_PANEL_INSET above.
//
// ContestantPanel: `left-4 w-72` (contestant-panel.tsx) = 16 + 288.
const CONTESTANT_PANEL_INSET = 304;
// ConversationPanel: `bottom-4` + header (~37) + `max-h-52` body (208), a
// deliberate over-estimate since the body shrinks with a short transcript --
// over-reserving pushes the pair slightly higher on screen, under-reserving
// hides them behind the panel, and only one of those is a bug.
const CONV_PANEL_INSET = 264;
// A chrome inset is only honored while it still leaves a usable play area. On
// a 390px phone the ContestantPanel covers 304 of 390, so applying it would
// squeeze the followed pair into an 86px sliver -- worse than ignoring it.
// Above this fraction of the viewport the inset is dropped entirely.
const CHROME_INSET_MAX_FRACTION = 0.4;

// --- Follow camera (the user's ask 1) --------------------------------------
// Default zoom rung: high enough to read faces and bubbles, low enough that an
// interaction pair and their speech bubbles fit. See followPad() for how the
// camera is held AT this rung rather than being allowed to climb past it.
const FOLLOW_ZOOM_RUNG = 2;
// Sentinel written into store.followedContestantId to mean "follow my
// investments" rather than one specific islander. Contestant ids are UUIDs
// (randomUUID server-side), so a plain word can never collide with one.
export const FOLLOW_PORTFOLIO_ID = "portfolio";
// Minimum time the portfolio camera stays on one holding before it may cut to
// a more interesting one, so a flurry of events cannot thrash the view.
const FOLLOW_DWELL_MS = 6000;
// How far back an event still counts toward "most interesting holding", and
// how its weight decays across that window.
const FOLLOW_INTEREST_WINDOW_MS = 12000;
// Allowances added around the framed box so the things that hang off a sprite
// are never clipped. Authored in SCREEN pixels because that is what they
// actually are: the tag pill and the speech bubble both render counter-scaled
// by 1/zoom (see update()), so their on-screen size is fixed and their WORLD
// size GROWS as the camera zooms out. followPadWorld() therefore converts them
// at the live zoom. Baking the world size in at one rung -- which is what this
// did first -- is correct only at that rung and under-reserves headroom at
// every wider one, and a wider rung is exactly the case a spread-out pair
// forces, so that is precisely when a three-line bubble got clipped off the
// top of the viewport.
//
// Sideways: half a speech bubble, BUBBLE_WRAP_W (132) + BUBBLE_PAD_X * 2 (10),
// halved = 71.
//
// Upward, measured from the sprite's FEET (its origin) through the tallest
// stack that can ever sit above it: the pill's half height above its center
// (~10) + BUBBLE_GAP (3) + BUBBLE_TAIL_H (4) + a three-line bubble body
// (BUBBLE_MAX_LINES at ~13px line height + BUBBLE_PAD_Y * 2 = ~47) = ~64.
// Rounded up to 76 for headroom: over-reserving only pushes the pair slightly
// lower in frame, under-reserving clips the top line of a bubble, and only one
// of those is a bug (same reasoning as CONV_PANEL_INSET above). The head
// offset itself (CHAR_ORIGIN_Y * CHAR_FRAME_H + PILL_GAP) is NOT counter-
// scaled -- update() applies it in world units -- so it is added separately,
// unconverted, in followPadWorld.
const FOLLOW_PAD_SIDE_SCREEN = 71;
const FOLLOW_PAD_HEAD_SCREEN = 76;
// Floor for the zoom those screen allowances are converted at. Without it the
// conversion feeds back on itself: a wider rung inflates the world-space pad,
// which asks the framing for a wider rung again. Clamping the conversion at 1x
// makes the pad monotone and bounded, so the rung picker always settles. Below
// 1x there is nothing to protect anyway -- pills and bubbles are at or under
// PILL_MIN_ZOOM (0.75) and about to be hidden entirely.
const FOLLOW_PAD_ZOOM_FLOOR = 1;

// Exact flat color of the packed water tile (see generate-assets.mjs's
// `water` crop) -- used so the camera background is indistinguishable from
// the map's own water where the tilemap doesn't cover the viewport (wide
// screens at fit zoom, or panning past the map edge).
const OCEAN_BG = 0x32b8e8;

// Character spritesheet layout, mirroring generate-assets.mjs (CHAR_FRAME_W/H,
// CHAR_ORIGIN_Y, CHAR_ANIM). Every contestant uses the same look -- only the
// tag pill differentiates them -- so this is the one sprite the whole roster shares.
const CHAR_FRAME_W = 24;
const CHAR_FRAME_H = 22;
// Feet sit at a fixed fraction of the frame height (consistent across idle/
// walk/death), used as the sprite's vertical origin so it "stands" on its tile.
const CHAR_ORIGIN_Y = 19 / 22;
const CHAR_ANIM = {
  idle: { start: 0, end: 8 },
  walk: { start: 9, end: 16 },
  death: { start: 17, end: 29 },
} as const;

// Small gap above the sprite's head before the tag pill starts.
const PILL_GAP = 4;

type Entry = {
  sprite: Phaser.GameObjects.Sprite;
  pill: Phaser.GameObjects.Container;
  // Last interpolation-derived base position. Transient fight offsets render
  // on top of these coordinates and never mutate the base itself.
  renderX: number;
  renderY: number;
  moving: boolean;
  name: string;
  shownPct: number; // the integer % currently drawn on the pill
};

type Swimmer = {
  sprite: Phaser.GameObjects.Image;
  speed: number;
  baseY: number;
  phase: number;
  clearance: number;
};

type ConvNode = {
  container: Phaser.GameObjects.Container;
  icon: Phaser.GameObjects.Text;
  outcome: ClientConversation["outcome"];
};

// What's currently floating over a conversing sprite. `line` is the spoken text
// on show (null = the listening/idle dots), and is what syncConversations diffs
// against to decide whether the art needs rebuilding. `chat` records which of
// the two anchorings the container was built with, since update() has to
// position them differently and the flag must not be re-read per frame.
type VoiceBubble = {
  container: Phaser.GameObjects.Container;
  line: string | null;
  chat: boolean;
};

// Icon shown on an interaction marker: a speech glyph while the conversation
// is still ongoing (outcome is null), then a state-specific glyph once it ends.
//
// With outcomeIcons off this is the original three-way mapping, unchanged, so
// the island looks exactly as it does today. With it on the marker reads from
// the shared table in lib/outcomes.ts -- which is what finally gives truce,
// tension, and amicable their own glyphs and stops the island, the transcript
// panel, and the activity feed from disagreeing about what a truce looks like.
function convNodeGlyph(outcome: ClientConversation["outcome"]): string {
  if (islandFlags.outcomeIcons) return outcomePresentation(outcome).icon;
  if (outcome === "alliance") return "🤝"; // handshake
  if (outcome === "fight") return "⚔"; // crossed swords
  return "💬"; // ongoing conversation
}

// Normalize a spoken line for the bubble: collapse the whitespace (a stray
// newline would otherwise force a break the wrap never asked for) and hard-cap
// the length before wrapping. Returns null for a blank or missing line so the
// bubble degrades to the listening dots rather than rendering an empty box.
function bubbleLine(raw: string | undefined): string | null {
  const text = (raw ?? "").replace(/\s+/g, " ").trim();
  if (!text) return null;
  return text.length > BUBBLE_MAX_CHARS ? text.slice(0, BUBBLE_MAX_CHARS) : text;
}

// Conversation interaction nodes render above the trees so the marker is never
// hidden behind a canopy.
const CONV_NODE_DEPTH = 5;
// Love-Island hot pink for the interaction marker.
const CONV_NODE_COLOR = 0xff2d78;
// Voice icons and the fight clash spark render above the conv node so they're
// never hidden behind it when a fight breaks out mid-conversation.
const VOICE_ICON_DEPTH = 6;
// How far above the tag pill's center the (legacy, dots-only) voice icon sits.
const VOICE_ICON_OFFSET = 16;

// Chat bubble (calmConversations). Every number here is authored in SCREEN
// pixels, not world pixels: update() counter-scales the container by 1/zoom
// exactly like the tag pill, so what is written here is what a viewer actually
// sees at the default whole-island camera and at every other zoom rung.
const BUBBLE_WRAP_W = 132; // wrap width for the spoken line
const BUBBLE_PAD_X = 5;
const BUBBLE_PAD_Y = 4;
const BUBBLE_RADIUS = 4;
const BUBBLE_TAIL_W = 6;
const BUBBLE_TAIL_H = 4;
// Three wrapped lines is the most that can hang over a sprite before it starts
// swallowing its neighbors; anything longer is cut with an ellipsis. The
// transcript panel and the activity feed still carry the full text.
const BUBBLE_MAX_LINES = 3;
// Hard cap before wrapping, so one pathological line can never cost real layout
// work. Well above what three wrapped lines can show.
const BUBBLE_MAX_CHARS = 220;
// Clearance between the tag pill's top edge and the bubble's tail tip. The
// bubble hangs from that tip and grows UPWARD, so a three-line bubble and a
// one-line bubble both clear the name/odds pill by the same amount.
const BUBBLE_GAP = 3;
const BUBBLE_FILL = 0xffffff;
const BUBBLE_INK = "#20141c"; // near-black with a pink cast, to sit with the border
const BUBBLE_FADE_MS = 240;

// Built structures (villa/shrine/garden) and contestant sprites share this
// y-sorted band: depth = SORT_BASE + anchorY * SORT_Y_SCALE, where anchorY is
// a structure's base (bottom edge) or a sprite's current feet position. The
// scale is small enough that even the tallest map keeps this whole band well
// under CONV_NODE_DEPTH, so conv markers and voice icons always stay on top.
const SORT_BASE = 2;
const SORT_Y_SCALE = 0.001;
function characterDepth(y: number): number {
  return SORT_BASE + y * SORT_Y_SCALE;
}
// Built-structure landmark kinds that occlude/are-occluded-by contestants via
// the y-sort band above. Pond and dock stay at their fixed low depths -- they
// read as ground-level scenery, not walls a sprite could walk behind.
const STRUCTURE_KINDS = new Set<LandmarkPlacement["kind"]>(["villa", "shrine", "garden"]);

export class IslandScene extends Phaser.Scene {
  // Live roster (task 3.4): sprites keyed by contestant id, synced from the
  // socket layer's zustand store. Positions between store hydrations come
  // from the interpolation buffer, ~1 tick behind real time.
  private entries = new Map<string, Entry>();
  // Interaction nodes for active conversations (task 4.8), keyed by conv id.
  // Clickable -- clicking one opens the transcript panel for that
  // conversation; the icon shown swaps once the outcome lands.
  private convNodes = new Map<string, ConvNode>();
  // A sprite tap is recognized on pointer-up, after proving the pointer did
  // not become a camera drag or pinch. Coordinates stay in screen space for
  // that gesture test; selection converts the release point to world space.
  private tapCandidate: { pointerId: number; x: number; y: number } | null = null;
  // Speech bubbles shown above a sprite while its owner is in a live
  // conversation, keyed by contestant id (not conv id -- the bubble rides a
  // specific participant, and a contestant is only ever in one conversation
  // at a time).
  private voiceIcons = new Map<string, VoiceBubble>();
  // Transient lunge/shake offsets applied on top of the interpolated position
  // during a fight animation; layered in update() rather than tweening the
  // sprite directly so the animation doesn't fight the interpolation buffer.
  private fightOffsets = new Map<string, { x: number; y: number }>();
  // Tombstones left at death locations. They persist for the rest of the
  // game (cleaned up only when the contestant leaves the store entirely, e.g.
  // a reset) and stay clickable so the dead contestant's card can be opened.
  private tombstones = new Map<string, { container: Phaser.GameObjects.Container; x: number; y: number }>();
  // Little flags planted on the dock, one per voted-off islander -- the
  // boat-departure equivalent of a tombstone. Same lifetime + click-to-open-
  // card behavior as tombstones, just marking who sailed off rather than who
  // died. Spawned once the departing boat clears the map (boardAndSailOff).
  private dockFlags = new Map<string, { container: Phaser.GameObjects.Container; x: number; y: number }>();
  // Contestants whose death animation is playing; update() leaves them alone
  // and syncRoster won't re-trigger the sequence. A voted-off islander's boat
  // departure joins this same set (see boatDeparture) -- it needs the exact
  // same "stop driving this sprite" guarantee update()/selectNearestClickable/syncPills
  // already give a dying entry, just without the death animation or tombstone.
  private dying = new Set<string>();
  // World-space center of the map's "dock" landmark, captured once in
  // placeLandmarks; boatDeparture boards a voted-off islander here. Stays
  // null if the map has no dock, in which case boatDeparture falls back to
  // the nearest map edge.
  private dockWorld: { x: number; y: number } | null = null;
  // Boats mid-departure, keyed by contestant id, tracked only so a reset can
  // find and destroy one whose ride out to sea hasn't finished yet (see
  // syncRoster's `!c` branch) -- boatDeparture/boardAndSailOff otherwise
  // clean their own boat up on the normal completion path.
  private boats = new Map<string, Phaser.GameObjects.Image>();
  // The sail-off tween, keyed by contestant id. It's driven by a plain
  // { t } progress object rather than the sprite/boat directly (see
  // boardAndSailOff), so killTweensOf(sprite/boat) can't find and cancel it
  // on reset the way it can the walk-to-dock and boarding tweens -- this map
  // is what lets syncRoster's `!c` branch reach it directly instead.
  private sailTweens = new Map<string, Phaser.Tweens.Tween>();
  // Full map size in world pixels, captured in create(); used by
  // nearestEdgePoint to find where a departing boat sails off past the map's
  // border and out of view.
  private worldWidth = 0;
  private worldHeight = 0;
  private waterSparkles: Array<{ shape: Phaser.GameObjects.Rectangle; phase: number }> = [];
  private swimmers: Swimmer[] = [];
  private marineGround: number[][] = [];
  private marineTileSize = 16;
  private unsubscribeStore: (() => void) | null = null;
  private unsubscribeFight: (() => void) | null = null;
  // The camera controller's follow handle. Before this the return value of
  // createCameraController was discarded, so the follow mode it owns had no
  // way to be driven at all. Null only between construction and create().
  private cameraHandle: CameraControllerHandle | null = null;
  // Whether WE currently believe a follow is running. Diffed against
  // handle.isFollowing() every frame: the controller drops follow on any user
  // pan/zoom gesture (its GUARD 3) and when the target vanishes, and this is
  // how that release gets mirrored back into the store so the panel's Follow
  // toggle un-toggles itself.
  private followActive = false;
  // The store id the running follow was started for ("portfolio" included),
  // so a change of subject retargets instead of silently following the old one.
  private followId: string | null = null;
  // Portfolio mode's current subject and when it was chosen, for the dwell
  // minimum (see pickPortfolioSubject).
  private portfolioSubjectId: string | null = null;
  private portfolioSubjectAt = 0;
  // When each contestant was last seen in a fight, from the same fight:started
  // stream that drives the scuffle animation. Fights are the single most
  // watchable thing a holding can do, and they are not otherwise recoverable
  // from store state once the animation has played.
  private lastFightAt = new Map<string, number>();
  // Pixel rings under the viewer's own islander and every islander they hold
  // a position in. A map is required because a portfolio can contain several
  // agents at once; each ring is reconciled and positioned independently.
  private investmentRings = new Map<string, Phaser.GameObjects.Container>();

  constructor() {
    super("island");
  }

  preload(): void {
    this.load.image("tileset", "/assets/tileset.png");
    for (let i = 0; i < TREE_TEXTURE_COUNT; i++) {
      this.load.image(`tree${i}`, `/assets/tree${i}.png`);
    }
    for (const kind of LANDMARK_KINDS) {
      this.load.image(`landmark-${kind}`, `/assets/landmark-${kind}.png`);
    }
    this.load.spritesheet("contestant", "/assets/contestant.png", {
      frameWidth: CHAR_FRAME_W,
      frameHeight: CHAR_FRAME_H,
    });
    this.load.json("islandMap", "/assets/island-map.json");
  }

  create(): void {
    const map = this.cache.json.get("islandMap") as IslandMapData;
    const { tileSize, width, height, ground, decor, trees, landmarks } = map;

    const tilemap = this.make.tilemap({ tileWidth: tileSize, tileHeight: tileSize, width, height });
    // Packed tileset.png extrudes every tile by a 1px border (margin/spacing
    // below), mirroring apps/web/scripts/generate-assets.mjs (EXTRUDE) --
    // without it, sampling at the fractional fit-zoom rung bleeds a sliver of
    // the neighboring atlas tile into the edge of the current one.
    const tileset = tilemap.addTilesetImage("tiles", "tileset", tileSize, tileSize, 1, 2);
    if (!tileset) throw new Error("failed to register tileset image");

    const groundLayer = tilemap.createBlankLayer("ground", tileset, 0, 0, width, height);
    const decorLowLayer = tilemap.createBlankLayer("decorLow", tileset, 0, 0, width, height);
    const decorHighLayer = tilemap.createBlankLayer("decorHigh", tileset, 0, 0, width, height);
    if (!groundLayer || !decorLowLayer || !decorHighLayer) {
      throw new Error("failed to create tilemap layers");
    }

    groundLayer.putTilesAt(ground, 0, 0);
    groundLayer.setDepth(0);

    // Split decor: small ground clutter (bush, flowers) renders under
    // contestants; tall/blocking decor (rock) renders over them so sprites
    // can walk "behind" a boulder.
    const isLow = (v: number) => v === BUSH || v === FLOWER_A || v === FLOWER_B || v === FLOWER_C;
    const isHigh = (v: number) => v === ROCK;
    const decorLow = decor.map((row) => row.map((v) => (isLow(v) ? v : BLANK)));
    const decorHigh = decor.map((row) => row.map((v) => (isHigh(v) ? v : BLANK)));
    decorLowLayer.putTilesAt(decorLow, 0, 0);
    decorLowLayer.setDepth(1);
    decorHighLayer.putTilesAt(decorHigh, 0, 0);
    decorHighLayer.setDepth(1.6); // below contestants (2) so rocks never cover a sprite

    this.createMarineTextures();
    this.createLandmarkTextures();
    this.placeWaterSparkles(ground, tileSize);
    this.placeMarineLife(ground, tileSize);

    const worldW = width * tileSize;
    const worldH = height * tileSize;
    this.worldWidth = worldW;
    this.worldHeight = worldH;

    this.createAnimations();
    this.placeLandmarks(landmarks ?? [], tileSize);
    this.placeTrees(trees, tileSize);

    // Live roster sync: place whatever the store already has (snapshot often
    // hydrates before the scene boots), then subscribe for later joins,
    // deaths, and resets. syncRoster is idempotent, so either ordering is
    // safe.
    this.syncRoster();
    this.syncConversations();
    this.unsubscribeStore = useGameStore.subscribe(() => {
      this.syncRoster();
      this.syncConversations();
      this.syncPills();
    });
    // Fight-start flash + scuffle (Phase 5): a one-shot red pop plus a lunge/
    // shake/clash-spark animation on both combatants. Combat itself is
    // server-internal, so this one event is all the visual has to work with.
    this.unsubscribeFight = onFight((aId, bId) => {
      this.flashCombatant(aId);
      this.flashCombatant(bId);
      this.playFightAnimation(aId, bId);
      // Also the freshest "something worth watching is happening to this
      // islander" signal the portfolio camera has (see portfolioInterest).
      const now = Date.now();
      this.lastFightAt.set(aId, now);
      this.lastFightAt.set(bId, now);
    });
    // A tap selects on release, while a drag/pinch is owned exclusively by
    // the camera controller. Selecting on pointer-down made every pan that
    // began near an islander open a contestant panel.
    const TAP_SLOP_PX = 8;
    const onPointerDown = (pointer: Phaser.Input.Pointer) => {
      const downPointers = this.input.manager.pointers.filter((p) => p.active && p.isDown);
      if (downPointers.length > 1) {
        this.tapCandidate = null;
        return;
      }
      this.tapCandidate = { pointerId: pointer.id, x: pointer.x, y: pointer.y };
    };
    const onPointerMove = (pointer: Phaser.Input.Pointer) => {
      const tap = this.tapCandidate;
      if (!tap || tap.pointerId !== pointer.id) return;
      if (Math.hypot(pointer.x - tap.x, pointer.y - tap.y) > TAP_SLOP_PX) {
        this.tapCandidate = null;
      }
    };
    const onPointerUp = (pointer: Phaser.Input.Pointer) => {
      const tap = this.tapCandidate;
      this.tapCandidate = null;
      if (!tap || tap.pointerId !== pointer.id) return;
      if (Math.hypot(pointer.x - tap.x, pointer.y - tap.y) > TAP_SLOP_PX) return;
      const world = pointer.positionToCamera(this.cameras.main) as Phaser.Math.Vector2;
      this.selectNearestClickable(world.x, world.y);
    };
    const cancelTap = () => {
      this.tapCandidate = null;
    };
    this.input.on(Phaser.Input.Events.POINTER_DOWN, onPointerDown);
    this.input.on(Phaser.Input.Events.POINTER_MOVE, onPointerMove);
    this.input.on(Phaser.Input.Events.POINTER_UP, onPointerUp);
    this.input.on(Phaser.Input.Events.POINTER_UP_OUTSIDE, cancelTap);
    this.input.on("pointercancel", cancelTap);

    const cleanupScene = () => {
      this.unsubscribeStore?.();
      this.unsubscribeStore = null;
      this.unsubscribeFight?.();
      this.unsubscribeFight = null;
      // Follow + owned-marker state lives on the scene INSTANCE, which outlives
      // a shutdown, while every GameObject it points at does not. Clearing it
      // here means a scene restart re-derives both from scratch on the next
      // frame instead of driving a destroyed container or believing it is still
      // following through a camera controller that no longer exists.
      this.cameraHandle = null;
      this.followActive = false;
      this.followId = null;
      this.portfolioSubjectId = null;
      this.portfolioSubjectAt = 0;
      this.lastFightAt.clear();
      this.investmentRings.clear();
      this.tapCandidate = null;
      this.input.off(Phaser.Input.Events.POINTER_DOWN, onPointerDown);
      this.input.off(Phaser.Input.Events.POINTER_MOVE, onPointerMove);
      this.input.off(Phaser.Input.Events.POINTER_UP, onPointerUp);
      this.input.off(Phaser.Input.Events.POINTER_UP_OUTSIDE, cancelTap);
      this.input.off("pointercancel", cancelTap);

      // A Scene instance can be restarted after shutdown, but its display-list
      // GameObjects cannot. Clear every scene-owned registry so syncRoster and
      // syncConversations respawn fresh objects instead of finding stale IDs
      // that point at destroyed sprites.
      this.entries.clear();
      this.convNodes.clear();
      this.voiceIcons.clear();
      this.fightOffsets.clear();
      this.tombstones.clear();
      this.dockFlags.clear();
      this.dying.clear();
      this.boats.clear();
      this.sailTweens.clear();
      this.waterSparkles = [];
      this.swimmers = [];
      this.marineGround = [];
      this.dockWorld = null;
      this.worldWidth = 0;
      this.worldHeight = 0;
    };
    // A normal scene stop emits SHUTDOWN, but React Strict Mode/HMR tears the
    // whole Phaser game down and Phaser can emit DESTROY directly. Listen for
    // both so dead scene subscriptions and input handlers cannot survive a
    // reload and receive later roster or pointer events.
    this.events.once(Phaser.Scenes.Events.SHUTDOWN, cleanupScene);
    this.events.once(Phaser.Scenes.Events.DESTROY, cleanupScene);

    const camera = this.cameras.main;
    camera.setBounds(0, 0, worldW, worldH);
    // Matches the packed water tile's flat color exactly (see OCEAN_BG) so
    // the sea reads as continuous out to every viewport edge, at any zoom,
    // wherever the tilemap itself doesn't cover the screen.
    camera.setBackgroundColor(OCEAN_BG);

    // Default view always shows the whole island; zoom ladder floor is
    // whatever "fit the viewport" computes to (fractional on small phones).
    // The handle is KEPT now (it used to be discarded): it owns the follow
    // mode, and update() drives it once per frame from the same interpolated
    // positions the sprites are drawn at.
    this.cameraHandle = createCameraController(this, camera, {
      worldWidth: worldW,
      worldHeight: worldH,
      // The authored map includes a generous ocean border, so a modest
      // presentation zoom makes the island itself occupy more of the screen
      // without cutting into its playable shoreline.
      fitScale: 1.12,
      // Desktop (Tailwind md+, >=768px) shows the activity-feed rail: w-80
      // (320px) plus its 16px right margin. Below that the feed is hidden and
      // the whole width is island. Keep this in sync with the rail geometry in
      // src/app/page.tsx.
      getRightInset: () => this.rightInset(),
      // Left/bottom chrome is consulted only while following (the controller's
      // GUARD 2b); these read live store state because both panels open and
      // close under the viewer while the camera is locked on.
      getLeftInset: () => this.leftInset(),
      getBottomInset: () => this.bottomInset(),
    });
  }

  private createAnimations(): void {
    if (!this.anims.exists("idle")) {
      this.anims.create({
        key: "idle",
        frames: this.anims.generateFrameNumbers("contestant", CHAR_ANIM.idle),
        frameRate: 6,
        repeat: -1,
      });
    }
    if (!this.anims.exists("walk")) {
      this.anims.create({
        key: "walk",
        frames: this.anims.generateFrameNumbers("contestant", CHAR_ANIM.walk),
        frameRate: 10,
        repeat: -1,
      });
    }
    if (!this.anims.exists("death")) {
      this.anims.create({
        key: "death",
        frames: this.anims.generateFrameNumbers("contestant", CHAR_ANIM.death),
        frameRate: 10,
        repeat: 0,
      });
    }
  }

  update(_time: number, delta: number): void {
    const renderTime = Date.now() - RENDER_DELAY_MS;
    const camera = this.cameras.main;
    const shimmerTime = this.time.now * 0.0024;
    for (const sparkle of this.waterSparkles) {
      sparkle.shape.setAlpha(0.18 + 0.42 * (0.5 + 0.5 * Math.sin(shimmerTime + sparkle.phase)));
    }
    this.updateMarineLife(Math.min(delta, 50));
    // Below the desktop-fit ballpark (~0.88), constant-screen-size pills
    // would need to render *bigger* than authored to stay legible -- fine at
    // desktop fit, but at phone fit (~0.4) that's most of the screen turning
    // into pill clutter over a crowd of 40. Product call: hide pills
    // entirely below this threshold: the phone fit view is ambient, and the
    // market list (drawer) carries the per-contestant detail instead. Above
    // it, scale exactly 1/zoom for a constant on-screen size at every zoom.
    const PILL_MIN_ZOOM = 0.75;
    const showPills = camera.zoom >= PILL_MIN_ZOOM;
    const pillScale = 1 / camera.zoom;
    const view = camera.worldView;
    const headOffset = CHAR_ORIGIN_Y * CHAR_FRAME_H + PILL_GAP;

    for (const entry of this.entries.values()) {
      const { sprite, pill } = entry;
      // A dying sprite is running its death animation + fade; don't drive its
      // position or swap it back to walk/idle.
      if (this.dying.has(sprite.name)) continue;
      const pos = samplePosition(sprite.name, renderTime);
      if (pos) {
        if (pos.x < entry.renderX) sprite.setFlipX(true);
        else if (pos.x > entry.renderX) sprite.setFlipX(false);
        entry.renderX = pos.x;
        entry.renderY = pos.y;
        if (pos.moving !== entry.moving) {
          entry.moving = pos.moving;
          sprite.play(pos.moving ? "walk" : "idle");
        }
      }
      // Fight lunge/shake (if any) rides on top of the interpolated base
      // position rather than replacing it. Always derive from renderX/Y;
      // adding to sprite.x/y accumulated offsets if an interpolation sample
      // was briefly absent and produced the reported visual trail/drift.
      const offset = this.fightOffsets.get(sprite.name);
      sprite.setPosition(
        entry.renderX + (offset?.x ?? 0),
        entry.renderY + (offset?.y ?? 0),
      );
      // 2.5D y-sort: recompute every frame from the sprite's *current* y so a
      // walking sprite continuously slots in front of / behind built
      // structures as it crosses their base line. Pill and voice icon ride
      // just above the sprite's own depth so the whole group stays together.
      const depth = characterDepth(sprite.y);
      sprite.setDepth(depth);
      const pillY = sprite.y - headOffset;
      pill.setPosition(sprite.x, pillY);
      pill.setDepth(depth + 0.0002);
      const visible = showPills && view.contains(sprite.x, pillY);
      pill.setVisible(visible);
      if (visible) pill.setScale(pillScale);
      const bubble = this.voiceIcons.get(sprite.name);
      if (bubble) {
        // Two anchorings. The legacy dots indicator is centered on a fixed
        // offset above the pill. The chat bubble instead hangs its tail tip
        // just above the pill's TOP edge and grows upward, so however tall the
        // line wraps it can never reach down into the name/odds pill.
        //
        // The pill's height and the gap are authored in SCREEN pixels (the
        // pill renders counter-scaled by 1/zoom, just below), but this offset
        // is applied in WORLD units -- so it has to be converted by the same
        // pillScale. Without that it is only correct near zoom 1: at the 2x-4x
        // rungs the follow camera uses, the bubble floated tens of screen
        // pixels clear of the pill it is supposed to sit on, and below ~0.78 it
        // would have overlapped the pill (masked today only because pills hide
        // below PILL_MIN_ZOOM).
        const iconY = bubble.chat
          ? pillY - ((entry.pill.height || VOICE_ICON_OFFSET) / 2 + BUBBLE_GAP) * pillScale
          : pillY - VOICE_ICON_OFFSET;
        bubble.container.setPosition(sprite.x, iconY);
        bubble.container.setDepth(depth + 0.0003);
        // Same visibility rule as the pill (hidden at phone-fit zoom, culled
        // off-screen) and the same 1/zoom counter-scale, which is what keeps a
        // bubble legible at the default whole-island camera.
        const iconVisible = showPills && view.contains(sprite.x, iconY);
        bubble.container.setVisible(iconVisible);
        if (iconVisible) bubble.container.setScale(pillScale);
      }
    }

    // Everything below reads the positions the loop above just sampled, so it
    // has to run after it -- most of all the camera, which would otherwise
    // frame the pair one frame stale.
    this.syncConvNodePositions(renderTime);
    this.syncInvestmentMarkers(pillScale, view);
    this.updateFollow();
  }

  // ---------------------------------------------------------------------
  // Follow camera (the user's ask 1: follow my own agent, or the agents I
  // invested in, zoomed in and framed so their INTERACTIONS stay on screen).
  // ---------------------------------------------------------------------

  // A chrome inset is worth honoring only while it leaves a usable play area;
  // see CHROME_INSET_MAX_FRACTION.
  private chromeInset(px: number, viewport: number): number {
    return px <= viewport * CHROME_INSET_MAX_FRACTION ? px : 0;
  }

  // The desktop activity-feed rail. Unlike the other two this one IS modeled at
  // the fit rung as well, so it is handed to the controller as getRightInset in
  // create() and read here by the framing math -- one definition, two readers,
  // rather than the same breakpoint test written out twice.
  private rightInset(): number {
    return this.scale.width >= 768 ? FEED_PANEL_INSET : 0;
  }

  // The ContestantPanel is where the Follow control lives, so it is open for
  // essentially the entire time a follow is active -- without this the
  // followed pair sits behind the very panel used to start following.
  private leftInset(): number {
    if (useGameStore.getState().selectedContestantId === null) return 0;
    return this.chromeInset(CONTESTANT_PANEL_INSET, this.scale.width);
  }

  // The ConversationPanel (bottom-left) is what a viewer opens to read the
  // conversation they are watching, so it is the other panel that routinely
  // covers the thing being followed.
  private bottomInset(): number {
    if (useGameStore.getState().openConversationId === null) return 0;
    return this.chromeInset(CONV_PANEL_INSET, this.scale.height);
  }

  // The interpolated world position the camera should use for a contestant --
  // deliberately NOT sprite.x/y, which has the transient fight lunge/shake
  // offset baked into it in place (see update()), so a camera reading the
  // sprite would shake through every single fight. Returns null for anyone the
  // camera must not chase: not spawned, or mid-death / mid-boat-departure,
  // where the sprite is tween-driven and update() has stopped driving it.
  private followSample(id: string, renderTime: number): { x: number; y: number } | null {
    if (!this.entries.has(id) || this.dying.has(id)) return null;
    return samplePosition(id, renderTime);
  }

  // The live (not yet ended) conversation a contestant is in, if any. An
  // ended one is deliberately excluded: its participants are already walking
  // away, and framing a pair that is dispersing just zooms the camera out.
  private liveConversationFor(id: string): ClientConversation | null {
    const { conversations } = useGameStore.getState();
    for (const conv of Object.values(conversations)) {
      if (conv.endedAt === null && conv.participantIds.includes(id)) return conv;
    }
    return null;
  }

  // Which contestant the camera should actually be on for a given store value.
  // A plain contestant id resolves to itself; the portfolio sentinel resolves
  // to whichever holding is most worth watching right now.
  private followSubjectId(desired: string): string | null {
    if (desired !== FOLLOW_PORTFOLIO_ID) return desired;
    return this.pickPortfolioSubject(Date.now());
  }

  // PAIR-AWARE FRAMING. When the followed islander is mid-conversation, the
  // camera frames BOTH participants and their speech bubbles rather than the
  // one sprite -- otherwise the half of the interaction the viewer actually
  // wants to read sits off the edge of the screen.
  //
  // The live midpoint is recomputed from both participants' interpolated
  // positions every frame. ClientConversation.x/y is NOT used: it is frozen at
  // conv:started and never updated, so with calmConversations on (the pair
  // keeps shifting weight while they talk) it drifts away from the pair it
  // labels.
  private resolveFollowTarget(desired: string): CameraFollowTarget | null {
    const subject = this.followSubjectId(desired);
    if (!subject) return null;
    const renderTime = Date.now() - RENDER_DELAY_MS;
    const self = this.followSample(subject, renderTime);
    if (!self) return null;

    let minX = self.x;
    let maxX = self.x;
    let minY = self.y;
    let maxY = self.y;
    const conv = this.liveConversationFor(subject);
    if (conv) {
      for (const pid of conv.participantIds) {
        if (pid === subject) continue;
        const p = this.followSample(pid, renderTime);
        if (!p) continue; // a partner mid-death still leaves the subject framed
        minX = Math.min(minX, p.x);
        maxX = Math.max(maxX, p.x);
        minY = Math.min(minY, p.y);
        maxY = Math.max(maxY, p.y);
      }
    }

    // Sprite origins sit at the FEET, and the pill plus the speech bubble hang
    // above the head, so the box to keep on screen is asymmetric: it extends
    // the head allowance above the highest pair of feet and stops at the
    // lowest. Centering on that box (rather than on the sprites) is what biases
    // the camera to look higher and keeps a three-line bubble from being
    // clipped off the top of the viewport.
    const allowance = this.followPadWorld();
    const boxTop = minY - allowance.head;
    const boxBottom = maxY;
    return {
      x: (minX + maxX) / 2,
      y: (boxTop + boxBottom) / 2,
      pad: this.followPad((maxX - minX) / 2 + allowance.side, (boxBottom - boxTop) / 2),
    };
  }

  // World-space half-extents of everything that hangs off a sprite, AT THE
  // CAMERA'S CURRENT ZOOM. The pill and the bubble are counter-scaled, so their
  // world size is screen / zoom; the head offset is already world units and is
  // added unconverted. See the FOLLOW_PAD_*_SCREEN comment for the derivation
  // and for why the conversion zoom is floored.
  private followPadWorld(): { side: number; head: number } {
    const zoom = Math.max(FOLLOW_PAD_ZOOM_FLOOR, this.cameras.main.zoom);
    return {
      side: FOLLOW_PAD_SIDE_SCREEN / zoom,
      head: CHAR_ORIGIN_Y * CHAR_FRAME_H + PILL_GAP + FOLLOW_PAD_HEAD_SCREEN / zoom,
    };
  }

  // The half-extent handed to the camera's pad-aware framing, which picks the
  // highest ladder rung whose visible area still contains a box this big.
  //
  // Floored at the half-extent the DEFAULT rung implies, which is what turns
  // "highest rung that fits" into the behavior actually wanted here: hold
  // FOLLOW_ZOOM_RUNG normally, and back off to a wider rung only when the pair
  // has spread too far to frame at it. Without the floor a lone islander would
  // always be picked up at the tightest rung on the ladder (4x), which is an
  // unreadable close-up that anyone walking leaves within a second.
  private followPad(halfX: number, halfY: number): number {
    const camera = this.cameras.main;
    const availW = Math.max(1, camera.width - this.rightInset() - this.leftInset());
    const availH = Math.max(1, camera.height - this.bottomInset());
    const padAtDefaultRung = Math.min(availW, availH) / (2 * FOLLOW_ZOOM_RUNG);
    return Math.max(padAtDefaultRung, halfX, halfY);
  }

  // "FOLLOW MY INVESTMENTS": the most interesting living holding right now,
  // with a dwell minimum so the camera cannot thrash between two islanders
  // having a busy minute. Returns null when the viewer holds nothing living,
  // which releases the follow.
  private pickPortfolioSubject(now: number): string | null {
    const state = useGameStore.getState();
    const candidates = selectMyPositions(state)
      .filter((p) => p.yesShares > 0 || p.noShares > 0)
      .map((p) => p.contestantId)
      .filter(
        (id) =>
          state.contestants[id]?.alive &&
          this.followSample(id, now - RENDER_DELAY_MS) !== null,
      );
    if (candidates.length === 0) return null;

    const current = this.portfolioSubjectId;
    const held = current !== null && candidates.includes(current);
    if (held && now - this.portfolioSubjectAt < FOLLOW_DWELL_MS) return current;

    let bestId = candidates[0];
    let bestScore = -Infinity;
    for (const id of candidates) {
      const score = this.portfolioInterest(id, now, state);
      if (score > bestScore) {
        bestScore = score;
        bestId = id;
      }
    }
    if (bestId !== current) {
      this.portfolioSubjectId = bestId;
      this.portfolioSubjectAt = now;
    }
    return bestId;
  }

  // How much a holding is worth watching. Deliberately weighted the way the
  // spec weights outcomes: a fight or an alliance is drama, "nothing" and the
  // legacy "truce" are not, so a run full of truces cannot monopolize the
  // camera the way it monopolizes the transcript. Position size only breaks
  // ties between islanders nothing is happening to.
  private portfolioInterest(id: string, now: number, state: GameStore): number {
    let score = 0;

    const fightAt = this.lastFightAt.get(id);
    if (fightAt !== undefined && now - fightAt < FOLLOW_INTEREST_WINDOW_MS) {
      score += 40 * (1 - (now - fightAt) / FOLLOW_INTEREST_WINDOW_MS);
    }

    // The activity feed already carries every visible thing that happened to
    // an islander, tagged with who it involved, so it is the cheapest event
    // source available -- no second subscription needed. Only the tail is
    // scanned; anything older than the interest window scores zero anyway.
    const KIND_WEIGHT: Partial<Record<(typeof state.feed)[number]["kind"], number>> = {
      fight: 40,
      death: 40,
      event: 30,
      hostile: 24,
      alliance: 20,
      conv: 2,
      thought: 1,
    };
    for (let i = state.feed.length - 1; i >= 0 && i >= state.feed.length - 60; i--) {
      const entry = state.feed[i];
      const age = now - entry.t;
      if (age > FOLLOW_INTEREST_WINDOW_MS) break; // feed is ordered oldest-first
      if (!entry.contestantIds.includes(id)) continue;
      const recency = 1 - age / FOLLOW_INTEREST_WINDOW_MS;
      const weight =
        entry.kind === "outcome"
          ? isNotableOutcome(entry.outcome)
            ? 18
            : 0
          : (KIND_WEIGHT[entry.kind] ?? 0);
      score += weight * recency;
    }

    if (this.liveConversationFor(id) !== null) score += 12;

    const pos = selectMyPositions(state).find((p) => p.contestantId === id);
    if (pos) score += Math.min(6, (pos.yesShares + pos.noShares) * 0.02);
    return score;
  }

  // Reconciles the store's followedContestantId with the camera handle once
  // per frame, and drives the follow lerp. Three directions of change all land
  // here: the viewer starts/stops/retargets a follow from the panel, the
  // camera drops follow because of a pan/zoom gesture (its GUARD 3), and the
  // followed islander dies or sails off and the target stops resolving.
  private updateFollow(): void {
    const handle = this.cameraHandle;
    if (!handle) return;

    const state = useGameStore.getState();
    const desired = islandFlags.followCamera ? state.followedContestantId : null;

    if (desired === null) {
      // Includes the flag being off, in which case follow() is a no-op anyway
      // and the camera behaves exactly as it does today.
      if (this.followActive) {
        handle.stop();
        this.followActive = false;
        this.followId = null;
      }
      return;
    }

    if (this.followActive && !handle.isFollowing()) {
      // Released underneath us: either a user gesture won (drag / wheel /
      // pinch), or the target stopped resolving because the followed islander
      // died, sailed off, or -- in portfolio mode -- the last living holding
      // went. Mirror that back into the store so the panel's Follow toggle
      // reflects reality rather than claiming to still be following.
      this.followActive = false;
      this.followId = null;
      this.portfolioSubjectId = null;
      state.setFollowedContestantId(null);
      return;
    }

    if (!this.followActive || this.followId !== desired) {
      // A live accessor, not a snapshot: the camera polls it once per frame,
      // which is what lets the framing track a pair that is still moving.
      const getTarget = () => this.resolveFollowTarget(desired);
      // Nothing to lock onto yet (the sprite has not spawned, or the
      // portfolio is empty this instant) -- leave the camera alone and retry
      // next frame rather than starting a follow on stale coordinates.
      if (getTarget() === null) return;
      handle.follow(getTarget, { zoomRung: FOLLOW_ZOOM_RUNG });
      this.followActive = handle.isFollowing();
      this.followId = this.followActive ? desired : null;
      if (!this.followActive) return;
    }

    handle.update();
  }

  // Red pixel rings under the viewer's own islander and every agent in their
  // portfolio. Positions are authoritative spectator state, so a successful
  // investment creates its ring immediately when upsertPosition updates the
  // store; no separate socket event or polling is needed.
  //
  // spectator.ownedContestantId crossed the wire on every hello/join and had
  // zero readers before this marker existed, so the owned id remains part of
  // the marked set even before the viewer invests. A ground ring rather than
  // a crown or second pill keeps the marker clear of names and speech bubbles.
  private syncInvestmentMarkers(
    pillScale: number,
    view: Phaser.Geom.Rectangle,
  ): void {
    const state = useGameStore.getState();
    const markedIds = new Set(
      selectMyPositions(state)
        .filter((position) => position.yesShares > 0 || position.noShares > 0)
        .map((position) => position.contestantId),
    );
    const myId = selectMyContestantId(state);
    if (myId !== null) markedIds.add(myId);

    for (const [id, ring] of this.investmentRings) {
      const entry = this.entries.get(id);
      if (!markedIds.has(id) || entry === undefined || this.dying.has(id)) {
        ring.destroy();
        this.investmentRings.delete(id);
      }
    }

    for (const id of markedIds) {
      const entry = this.entries.get(id);
      if (entry === undefined || this.dying.has(id)) continue;
      let ring = this.investmentRings.get(id);
      if (!ring) {
        ring = this.buildInvestmentRing();
        this.investmentRings.set(id, ring);
      }
      const { sprite } = entry;
      ring.setPosition(sprite.x, sprite.y);
      // Just under the sprite's own depth so it reads as a decal on the ground
      // the islander is standing on rather than a halo over their shins.
      ring.setDepth(characterDepth(sprite.y) - 0.0001);
      const visible = view.contains(sprite.x, sprite.y);
      ring.setVisible(visible);
      if (visible) ring.setScale(pillScale);
    }
  }

  // A deliberately stepped, square-edged red ground ring. It is built from
  // integer-aligned rectangles instead of a smoothed Graphics ellipse so it
  // stays visibly pixelated at every camera rung. The pulse lives on the inner
  // container while update() counter-scales the outer container for zoom.
  private buildInvestmentRing(): Phaser.GameObjects.Container {
    const g = this.add.graphics();
    g.fillStyle(0xff2f2f, 1);
    g.fillRect(-6, -6, 12, 2);
    g.fillRect(-9, -4, 3, 2);
    g.fillRect(6, -4, 3, 2);
    g.fillRect(-11, -2, 3, 4);
    g.fillRect(8, -2, 3, 4);
    g.fillRect(-9, 2, 3, 2);
    g.fillRect(6, 2, 3, 2);
    g.fillRect(-6, 4, 12, 2);
    const inner = this.add.container(0, 0, [g]);
    const container = this.add.container(0, 0, [inner]);
    this.tweens.add({
      targets: inner,
      alpha: { from: 0.62, to: 1 },
      duration: 650,
      yoyo: true,
      repeat: -1,
      ease: "Linear",
    });
    return container;
  }

  // Keeps each interaction marker on its pair's live midpoint. The marker's
  // x/y is frozen at conv:started, and with calmConversations on the pair
  // keeps drifting while they talk, so the marker slowly walks away from the
  // conversation it labels. Only live conversations are re-anchored: once one
  // ends, the marker is showing the outcome OF A PLACE, and dragging it after
  // two islanders who are already leaving would be worse than leaving it.
  private syncConvNodePositions(renderTime: number): void {
    // Gated on the flag that creates the drift in the first place: with
    // calmConversations off the server pins conversing sprites, so the live
    // midpoint is the frozen point and this is a no-op either way.
    if (!islandFlags.calmConversations) return;
    const { conversations } = useGameStore.getState();
    for (const [id, node] of this.convNodes) {
      const conv = conversations[id];
      if (!conv || conv.endedAt !== null) continue;
      let sumX = 0;
      let sumY = 0;
      let n = 0;
      for (const pid of conv.participantIds) {
        const p = this.followSample(pid, renderTime);
        if (!p) continue;
        sumX += p.x;
        sumY += p.y;
        n++;
      }
      if (n === 0) continue; // nobody resolvable: leave the marker where it is
      node.container.setPosition(sumX / n, sumY / n);
    }
  }

  // Resolves a completed tap to the closest interaction marker. Conversation
  // nodes take priority over an islander standing directly beneath them; all
  // other targets -- a living sprite, tombstone, or dock flag -- compete by
  // distance. Selection lives here instead of on each GameObject's pointerdown
  // so starting a camera drag over a marker never opens a panel accidentally.
  private selectNearestClickable(wx: number, wy: number): void {
    const markerRadius = Math.max(12, 24 / this.cameras.main.zoom);
    let nearestConversation: string | null = null;
    let nearestConversationDistance = Infinity;
    for (const [id, node] of this.convNodes) {
      const d = Math.hypot(wx - node.container.x, wy - node.container.y);
      if (d < nearestConversationDistance) {
        nearestConversation = id;
        nearestConversationDistance = d;
      }
    }
    if (nearestConversation && nearestConversationDistance <= markerRadius) {
      useGameStore.getState().setOpenConversation(nearestConversation);
      return;
    }

    // Radius is zoom-aware so the effective tap target stays a comfortable
    // on-screen size at every zoom: ~26px screen radius (a ~52px target),
    // never smaller than the sprite body itself.
    // Keep the target roughly 52 screen pixels wide without letting the
    // sprite-body floor balloon at high zoom (the old 26.4-world floor became
    // a 211px-wide target at 4x and selected islanders from far away).
    const bodyRadius = Math.max(CHAR_FRAME_W, CHAR_FRAME_H) / 2;
    const radius = Math.max(bodyRadius, 26 / this.cameras.main.zoom);
    const bodyOffset = CHAR_ORIGIN_Y * CHAR_FRAME_H * 0.55;
    let bestId: string | null = null;
    let bestD = Infinity;
    const consider = (id: string, cx: number, cy: number) => {
      const d = Math.hypot(wx - cx, wy - cy);
      if (d < bestD) {
        bestD = d;
        bestId = id;
      }
    };
    for (const [id, entry] of this.entries) {
      if (this.dying.has(id)) continue;
      consider(id, entry.sprite.x, entry.sprite.y - bodyOffset);
    }
    // Tombstones and dock flags are stationary; their stored (x, y) is the
    // ground point, so lift the pick center by the same body offset for a
    // comfortable tap on the marker itself.
    for (const [id, t] of this.tombstones) consider(id, t.x, t.y - bodyOffset);
    for (const [id, f] of this.dockFlags) consider(id, f.x, f.y - bodyOffset);
    if (bestId && bestD <= radius) {
      useGameStore.getState().setSelectedContestant(bestId);
    }
  }

  private placeTrees(trees: TreePlacement[], tileSize: number): void {
    for (const t of trees) {
      const worldX = t.x * tileSize + tileSize / 2;
      // Anchor to the trunk tile's bottom edge, not its center, so the
      // canopy reads as "standing" on the ground instead of floating with
      // its base mid-tile.
      const worldY = t.y * tileSize + tileSize;
      const variant = t.variant >= 0 && t.variant < TREE_TEXTURE_COUNT ? t.variant : 0;
      const image = this.add.image(worldX, worldY, `tree${variant}`);
      image.setOrigin(0.5, 1);
      image.setScale(1.35);
      // Canopies never hide an islander. Large solid landmarks still use
      // y-sorting, but trees are ambient scenery and stay below the roster.
      image.setDepth(TREE_DEPTH);
    }
  }

  private createLandmarkTextures(): void {
    if (!this.textures.exists("landmark-garden-clean")) {
      const garden = this.add.graphics().setVisible(false);

      // Two tidy raised beds with a central stepping path. Keeping the edge
      // open makes this read as a usable garden instead of a broken fence.
      for (const x of [7, 47]) {
        garden.fillStyle(0x7a482a, 0.35).fillRect(x + 2, 13, 27, 42);
        garden.fillStyle(0x9d5b35, 1).fillRect(x, 10, 27, 42);
        garden.fillStyle(0xd18b4d, 1).fillRect(x, 10, 27, 3);
        garden.fillStyle(0x633b25, 1).fillRect(x, 49, 27, 3);
        garden.fillStyle(0x6d3b27, 1).fillRect(x + 4, 15, 19, 30);
        garden.fillStyle(0x875136, 1).fillRect(x + 5, 17, 17, 2);
        garden.fillRect(x + 5, 29, 17, 2);
        garden.fillRect(x + 5, 41, 17, 2);

        for (let row = 0; row < 3; row++) {
          for (let col = 0; col < 3; col++) {
            const plantX = x + 7 + col * 6;
            const plantY = 21 + row * 11;
            garden.fillStyle(0x296b35, 1).fillRect(plantX, plantY, 3, 5);
            garden.fillStyle(0x65b84b, 1).fillRect(plantX - 2, plantY + 1, 2, 3);
            garden.fillRect(plantX + 3, plantY, 2, 3);
            if ((row + col) % 2 === 0) garden.fillStyle(0xffd65a, 1).fillRect(plantX + 1, plantY - 2, 2, 2);
          }
        }
      }

      garden.fillStyle(0xd8c58b, 1);
      for (let y = 13; y < 58; y += 10) garden.fillRect(38, y, 4, 5);
      garden.fillStyle(0x724126, 1).fillRect(36, 2, 8, 9);
      garden.fillStyle(0xe0a65a, 1).fillRect(38, 4, 11, 6);
      garden.fillStyle(0x58a84b, 1).fillRect(41, 6, 5, 2);
      garden.generateTexture("landmark-garden-clean", 80, 64);
      garden.destroy();
    }

    if (!this.textures.exists("landmark-shrine-clean")) {
      const altar = this.add.graphics().setVisible(false);

      // A centered stone plaza, open toward the south, with a pink heart
      // altar and matching planters. The symmetry gives the landmark a clear
      // purpose and removes the previous maze-like wall fragments.
      altar.fillStyle(0x8aa3a6, 0.35).fillRect(15, 16, 68, 52);
      altar.fillStyle(0xc7d0c6, 1).fillRect(12, 12, 72, 48);
      altar.fillStyle(0xa9b7b1, 1).fillRect(8, 20, 80, 32);
      altar.fillStyle(0xdfe3d6, 1).fillRect(16, 16, 64, 40);
      altar.fillStyle(0xb9c6bd, 1).fillRect(20, 20, 56, 32);
      altar.fillStyle(0xd7d9c8, 1).fillRect(24, 24, 48, 24);
      altar.fillStyle(0xc6b88e, 1).fillRect(43, 48, 10, 32);
      altar.fillStyle(0xe8d9a9, 1).fillRect(46, 48, 4, 32);

      altar.fillStyle(0x65777a, 1).fillRect(36, 29, 24, 14);
      altar.fillStyle(0x9aa9a5, 1).fillRect(39, 25, 18, 15);
      altar.fillStyle(0xe7ece3, 1).fillRect(42, 23, 12, 4);
      altar.fillStyle(0xff3e7d, 1);
      altar.fillRect(43, 17, 5, 5);
      altar.fillRect(50, 17, 5, 5);
      altar.fillRect(41, 20, 16, 5);
      altar.fillRect(44, 25, 10, 4);
      altar.fillRect(47, 29, 4, 3);
      altar.fillStyle(0xff9db8, 1).fillRect(44, 18, 3, 2);

      for (const x of [18, 76]) {
        altar.fillStyle(0x76513a, 1).fillRect(x - 4, 37, 9, 8);
        altar.fillStyle(0x398247, 1).fillRect(x - 5, 31, 4, 7);
        altar.fillRect(x + 2, 30, 4, 8);
        altar.fillStyle(0xffd45b, 1).fillRect(x - 4, 29, 3, 3);
        altar.fillStyle(0xff79a5, 1).fillRect(x + 3, 28, 3, 3);
      }

      altar.generateTexture("landmark-shrine-clean", 96, 80);
      altar.destroy();
    }
  }

  private placeLandmarks(landmarks: LandmarkPlacement[], tileSize: number): void {
    for (const landmark of landmarks) {
      const texture = landmark.kind === "garden"
        ? "landmark-garden-clean"
        : landmark.kind === "shrine"
          ? "landmark-shrine-clean"
          : `landmark-${landmark.kind}`;
      const image = this.add.image(
        landmark.x * tileSize,
        landmark.y * tileSize,
        texture,
      );
      image.setOrigin(0, 0);
      if (landmark.kind === "villa") image.setScale(1.35);
      if (landmark.kind === "pond") {
        // Ponds replace the ground visually -- they read as flat water, not a
        // wall, so they stay at their own fixed low depth.
        image.setDepth(0.5);
      } else if (landmark.kind === "dock") {
        image.setDepth(1.5);
        // Origin is (0, 0), so image.x/y is the landmark's top-left corner --
        // record its center for boatDeparture to board departing islanders at.
        this.dockWorld = { x: image.x + image.displayWidth / 2, y: image.y + image.displayHeight / 2 };
      } else if (STRUCTURE_KINDS.has(landmark.kind)) {
        // Villa/shrine/garden are built structures: join the y-sorted band
        // shared with contestant sprites, anchored to the structure's base
        // (bottom edge) so a sprite standing "above" it on the map (smaller
        // y) renders behind its wall, and one standing "in front" (larger y)
        // renders over it.
        const baseY = landmark.y * tileSize + image.displayHeight;
        image.setDepth(characterDepth(baseY));
      } else {
        image.setDepth(1.9);
      }
    }
  }

  private placeWaterSparkles(ground: number[][], tileSize: number): void {
    this.waterSparkles = [];
    for (let y = 0; y < ground.length; y++) {
      for (let x = 0; x < ground[y].length; x++) {
        if (!WATER_TILE_INDICES.has(ground[y][x])) continue;
        const hash = (x * 37 + y * 61 + x * y * 3) >>> 0;
        if (hash % 29 !== 0) continue;
        const shape = this.add.rectangle(
          x * tileSize + 3 + (hash % 9),
          y * tileSize + 4 + ((hash >>> 3) % 8),
          hash % 3 === 0 ? 5 : 3,
          1,
          0xb9f1f5,
          0.4,
        );
        shape.setDepth(0.25);
        this.waterSparkles.push({ shape, phase: (hash % 31) * 0.37 });
      }
    }
  }

  private createMarineTextures(): void {
    if (this.textures.exists("marine-fish-school")) return;

    const fish = this.add.graphics().setVisible(false);
    const drawFish = (x: number, y: number, color: number) => {
      fish.fillStyle(color, 1);
      fish.fillRect(x + 3, y, 6, 4);
      fish.fillRect(x + 1, y + 1, 2, 2);
      fish.fillRect(x, y, 1, 1);
      fish.fillRect(x, y + 3, 1, 1);
      fish.fillStyle(0xe9fbff, 1);
      fish.fillRect(x + 8, y + 1, 1, 1);
    };
    drawFish(1, 1, 0xffd34f);
    drawFish(13, 6, 0xff6b6b);
    drawFish(5, 10, 0x547fea);
    fish.generateTexture("marine-fish-school", 24, 15);
    fish.destroy();

    const whale = this.add.graphics().setVisible(false);
    whale.fillStyle(0x28548a, 1);
    whale.fillRect(8, 4, 25, 11);
    whale.fillRect(12, 2, 16, 15);
    whale.fillRect(32, 6, 5, 7);
    whale.fillRect(3, 3, 5, 5);
    whale.fillRect(3, 11, 5, 5);
    whale.fillRect(0, 1, 4, 5);
    whale.fillRect(0, 13, 4, 5);
    whale.fillStyle(0x70b9cf, 1);
    whale.fillRect(15, 13, 16, 3);
    whale.fillRect(29, 11, 5, 3);
    whale.fillStyle(0xe9fbff, 1);
    whale.fillRect(31, 6, 2, 2);
    whale.fillStyle(0x102f55, 1);
    whale.fillRect(32, 6, 1, 1);
    whale.generateTexture("marine-whale", 38, 19);
    whale.destroy();

    const star = this.add.graphics().setVisible(false);
    star.fillStyle(0xff8a3d, 1);
    star.fillRect(4, 0, 2, 10);
    star.fillRect(0, 4, 10, 2);
    star.fillRect(2, 2, 6, 6);
    star.fillStyle(0xffcf63, 1);
    star.fillRect(4, 4, 2, 2);
    star.generateTexture("marine-starfish", 10, 10);
    star.destroy();
  }

  private placeMarineLife(ground: number[][], tileSize: number): void {
    this.marineGround = ground;
    this.marineTileSize = tileSize;
    this.swimmers = [];

    const isWater = (x: number, y: number) => WATER_TILE_INDICES.has(ground[y]?.[x] ?? -1);
    const nearIsland = (x: number, y: number) => {
      for (let dy = -5; dy <= 5; dy++) {
        for (let dx = -5; dx <= 5; dx++) {
          if (dx * dx + dy * dy > 25) continue;
          if (!isWater(x + dx, y + dy)) return true;
        }
      }
      return false;
    };
    const clearWater = (x: number, y: number, radius: number) => {
      for (let dy = -radius; dy <= radius; dy++) {
        for (let dx = -radius; dx <= radius; dx++) if (!isWater(x + dx, y + dy)) return false;
      }
      return true;
    };
    const hashAt = (x: number, y: number) => ((x * 73856093) ^ (y * 19349663)) >>> 0;

    const waterCandidates: Array<{ x: number; y: number; hash: number }> = [];
    const beachCandidates: Array<{ x: number; y: number; hash: number }> = [];
    for (let y = 1; y < ground.length - 1; y++) {
      for (let x = 1; x < ground[y].length - 1; x++) {
        const hash = hashAt(x, y);
        if (isWater(x, y) && nearIsland(x, y)) waterCandidates.push({ x, y, hash });
        if (BEACH_TILE_INDICES.has(ground[y][x])) beachCandidates.push({ x, y, hash });
      }
    }
    waterCandidates.sort((a, b) => a.hash - b.hash);
    beachCandidates.sort((a, b) => a.hash - b.hash);

    const takeSpaced = (
      candidates: Array<{ x: number; y: number; hash: number }>,
      count: number,
      minDistance: number,
      predicate: (c: { x: number; y: number; hash: number }) => boolean,
    ) => {
      const chosen: Array<{ x: number; y: number; hash: number }> = [];
      for (const candidate of candidates) {
        if (!predicate(candidate)) continue;
        if (chosen.every((other) => Math.hypot(candidate.x - other.x, candidate.y - other.y) >= minDistance)) {
          chosen.push(candidate);
          if (chosen.length === count) break;
        }
      }
      return chosen;
    };

    const centerX = (ground[0]?.length ?? 60) / 2;
    const westWater = waterCandidates.filter((candidate) => candidate.x < centerX - 2);
    const eastWater = waterCandidates.filter((candidate) => candidate.x > centerX + 2);
    const fishSpots = [
      ...takeSpaced(westWater, 5, 6, (c) => clearWater(c.x, c.y, 1)),
      ...takeSpaced(eastWater, 5, 6, (c) => clearWater(c.x, c.y, 1)),
    ];

    for (const spot of fishSpots) {
      const speed = (spot.hash & 1 ? 1 : -1) * (5 + (spot.hash % 5));
      const sprite = this.add.image(
        spot.x * tileSize + tileSize / 2,
        spot.y * tileSize + tileSize / 2,
        "marine-fish-school",
      );
      sprite.setDepth(0.46).setAlpha(0.88).setFlipX(speed < 0);
      this.swimmers.push({ sprite, speed, baseY: sprite.y, phase: (spot.hash % 41) * 0.3, clearance: 14 });
    }

    const centerY = ground.length / 2;
    const nearestClearWater = (
      candidates: Array<{ x: number; y: number; hash: number }>,
      targetX: number,
      targetY: number,
    ) =>
      candidates
        .filter((candidate) => clearWater(candidate.x, candidate.y, 3))
        .reduce<{ x: number; y: number; hash: number } | undefined>((nearest, candidate) => {
          if (!nearest) return candidate;
          const nearestDistance = Math.hypot(nearest.x - targetX, nearest.y - targetY);
          const candidateDistance = Math.hypot(candidate.x - targetX, candidate.y - targetY);
          return candidateDistance < nearestDistance ? candidate : nearest;
        }, undefined);
    const whaleSpots = [
      nearestClearWater(westWater, centerX - 18, centerY),
      nearestClearWater(eastWater, centerX + 18, centerY),
    ].filter((spot): spot is { x: number; y: number; hash: number } => spot !== undefined);
    for (const spot of whaleSpots) {
      const speed = (spot.hash & 1 ? 1 : -1) * (3 + (spot.hash % 2));
      const sprite = this.add.image(
        spot.x * tileSize + tileSize / 2,
        spot.y * tileSize + tileSize / 2,
        "marine-whale",
      );
      sprite.setDepth(0.44).setAlpha(0.9).setFlipX(speed < 0);
      this.swimmers.push({ sprite, speed, baseY: sprite.y, phase: (spot.hash % 29) * 0.4, clearance: 24 });
    }

    for (const spot of takeSpaced(beachCandidates, 12, 4, () => true)) {
      const star = this.add.image(
        spot.x * tileSize + 3 + (spot.hash % 9),
        spot.y * tileSize + 3 + ((spot.hash >>> 4) % 9),
        "marine-starfish",
      );
      star.setDepth(0.7).setAngle((spot.hash % 4) * 90).setScale(spot.hash % 3 === 0 ? 0.8 : 1);
      if (spot.hash % 2 === 0) star.setTint(0xffb347);
    }
  }

  private updateMarineLife(delta: number): void {
    const isWaterAt = (worldX: number, worldY: number) => {
      const x = Math.floor(worldX / this.marineTileSize);
      const y = Math.floor(worldY / this.marineTileSize);
      return WATER_TILE_INDICES.has(this.marineGround[y]?.[x] ?? -1);
    };
    for (const swimmer of this.swimmers) {
      const nextX = swimmer.sprite.x + (swimmer.speed * delta) / 1000;
      const direction = Math.sign(swimmer.speed);
      if (!isWaterAt(nextX + direction * swimmer.clearance, swimmer.baseY)) {
        swimmer.speed *= -1;
        swimmer.sprite.setFlipX(swimmer.speed < 0);
      } else {
        swimmer.sprite.x = nextX;
      }
      swimmer.sprite.y = swimmer.baseY + Math.sin(this.time.now * 0.002 + swimmer.phase) * 1.5;
    }
  }

  // Diffs the sprite map against the store roster: spawns new living
  // contestants, removes the dead and the reset-away. Safe to call
  // repeatedly with identical state.
  private syncRoster(): void {
    const { contestants, markets } = useGameStore.getState();

    for (const [id, entry] of this.entries) {
      const c = contestants[id];
      if (!c) {
        // Reset / vanished: remove immediately, cancelling any death tween
        // (or, for a voted-off islander mid-departure, the walk/board tween
        // plus the sail-off tween and its boat).
        this.tweens.killTweensOf([entry.sprite, entry.pill]);
        const sailTween = this.sailTweens.get(id);
        if (sailTween) {
          this.tweens.remove(sailTween);
          this.sailTweens.delete(id);
        }
        entry.sprite.destroy();
        entry.pill.destroy();
        const boat = this.boats.get(id);
        if (boat) {
          boat.destroy();
          this.boats.delete(id);
        }
        forget(id);
        this.entries.delete(id);
        this.dying.delete(id);
      } else if (!c.alive && !this.dying.has(id)) {
        // A voted-off islander isn't "killed" -- they leave the island by
        // boat instead of the flash/death-anim/tombstone path everyone else
        // (combat, purge, weakest link) takes.
        const cause = useGameStore.getState().contestants[id]?.causeOfDeath;
        if (cause === "voteOff") {
          this.boatDeparture(id, entry);
        } else {
          // Death choreography (task 5.5): flash, play the death animation,
          // fade, then remove.
          this.killEntry(id, entry);
        }
      }
    }

    // Normalized win odds across the living, unsettled markets, so a new pill
    // spawns showing its coherent "chance to win" (summing to ~100% with the
    // rest of the board) rather than the raw, un-normalized priceYes. The
    // living+unsettled filter lives in one place now (gameStore's
    // normalizedWinProbs) instead of being re-derived by convention here.
    const spawnProbs = normalizedWinProbs(markets, contestants);
    for (const c of Object.values(contestants)) {
      if (!c.alive || this.entries.has(c.id)) continue;
      this.spawnSprite(c, spawnProbs.get(c.id) ?? markets[c.id]?.priceYes ?? 0);
    }

    // Tombstones outlive the contestant's sprite (they mark where someone
    // died), but not the contestant's record in the store: once a reset
    // replaces the whole roster and the id is gone entirely, drop the stone.
    for (const [id, t] of this.tombstones) {
      if (!contestants[id]) {
        t.container.destroy();
        this.tombstones.delete(id);
      }
    }
    // Dock flags follow the same rule: they persist for the game but drop once
    // the voted-off islander's record leaves the store entirely (a reset).
    for (const [id, f] of this.dockFlags) {
      if (!contestants[id]) {
        f.container.destroy();
        this.dockFlags.delete(id);
      }
    }
  }

  private killEntry(id: string, entry: Entry): void {
    this.dying.add(id);
    const s = entry.sprite;
    s.setTint(0xffffff); // brief white flash on the killing blow
    s.play("death");
    this.time.delayedCall(160, () => {
      if (s.active) s.clearTint();
    });
    this.tweens.add({
      targets: [s, entry.pill],
      alpha: 0,
      duration: 900,
      delay: 500,
      onComplete: () => {
        const deathX = s.x;
        const deathY = s.y;
        s.destroy();
        entry.pill.destroy();
        forget(id);
        this.entries.delete(id);
        this.dying.delete(id);
        this.spawnTombstone(id, deathX, deathY);
      },
    });
  }

  // Left where a contestant died, once their death animation finishes.
  // Persists for the rest of the game and is clickable so the character card
  // can still be opened for the dead -- the contestant stays in the store
  // after death, so setSelectedContestant works exactly as it does while
  // they were alive.
  private spawnTombstone(id: string, x: number, y: number): void {
    const g = this.add.graphics();
    g.fillStyle(0x8a887f, 1);
    g.fillRect(-5, -10, 10, 10);
    g.fillTriangle(-5, -10, 5, -10, 0, -15);
    g.lineStyle(1, 0x4d4a43, 1);
    g.strokeRect(-5, -10, 10, 10);
    g.strokeTriangle(-5, -10, 5, -10, 0, -15);
    // A small etched cross, just enough detail to read as a grave marker at
    // a glance.
    g.fillStyle(0x4d4a43, 1);
    g.fillRect(-2, -7, 4, 1);
    g.fillRect(-1, -8, 1, 3);
    const container = this.add.container(x, y, [g]);
    // Stationary, so a one-time y-sort depth (matching where a living sprite
    // would sort at this y) is enough -- it never needs recomputing.
    container.setDepth(characterDepth(y));
    this.tombstones.set(id, { container, x, y });
  }

  // A small hot-pink pennant planted on the dock for a voted-off islander,
  // planted where their boat departed. Multiple voted-off islanders line the
  // dock in a small grid (offset by how many flags already stand) so they
  // don't overlap. Like a tombstone: stationary, persists for the game, and
  // clickable to reopen the departed islander's card.
  private spawnDockFlag(id: string, board: { x: number; y: number }): void {
    if (this.dockFlags.has(id)) return;
    const idx = this.dockFlags.size;
    const col = idx % 5;
    const row = Math.floor(idx / 5);
    // Fan out along the dock and step up the pier (smaller y) so flags stand on
    // the planks rather than in the water below the boarding point.
    const x = board.x - 18 + col * 9;
    const y = board.y - 10 - row * 12;

    const g = this.add.graphics();
    // Pole.
    g.fillStyle(0x4d3018, 1);
    g.fillRect(-1, -16, 2, 16);
    // Hot-pink pennant (on-brand accent), pointing right off the pole top.
    g.fillStyle(CONV_NODE_COLOR, 1);
    g.fillTriangle(1, -16, 1, -8, 11, -12);
    // Little base so the pole reads as planted, not floating.
    g.fillStyle(0x6d4225, 1);
    g.fillRect(-3, -1, 6, 2);

    const container = this.add.container(x, y, [g]);
    container.setDepth(characterDepth(y));
    this.dockFlags.set(id, { container, x, y });
  }

  // Point just past whichever map edge (x, y) is closest to, i.e. off the
  // world bounds and out of camera view -- used both as the fallback boarding
  // spot when the map has no dock, and as the boat's sail-off destination.
  private nearestEdgePoint(x: number, y: number): { x: number; y: number } {
    const w = this.worldWidth;
    const h = this.worldHeight;
    const OFF = 80; // past the border, comfortably off-screen at any zoom
    const edges: Array<{ dist: number; point: { x: number; y: number } }> = [
      { dist: x, point: { x: -OFF, y } },
      { dist: w - x, point: { x: w + OFF, y } },
      { dist: y, point: { x, y: -OFF } },
      { dist: h - y, point: { x, y: h + OFF } },
    ];
    edges.sort((a, b) => a.dist - b.dist);
    return edges[0].point;
  }

  // Small pixel boat -- brown hull, mast, off-white sail with a hot-pink flag
  // (on-brand accent) -- generated once with graphics the same way
  // createLandmarkTextures/createMarineTextures build their own art.
  private ensureBoatTexture(): void {
    if (this.textures.exists("boat")) return;
    const g = this.add.graphics().setVisible(false);
    g.fillStyle(0x8a5a34, 1);
    g.fillRect(2, 16, 24, 6);
    g.fillTriangle(2, 16, 0, 22, 6, 22);
    g.fillTriangle(26, 16, 28, 22, 22, 22);
    g.fillStyle(0x6d4225, 1);
    g.fillRect(2, 20, 24, 2);
    g.fillStyle(0x4d3018, 1);
    g.fillRect(13, 2, 2, 15);
    g.fillStyle(0xf6efe2, 1);
    g.fillTriangle(15, 3, 15, 15, 25, 14);
    g.fillStyle(CONV_NODE_COLOR, 1);
    g.fillTriangle(15, 2, 15, 6, 20, 4);
    g.generateTexture("boat", 28, 24);
    g.destroy();
  }

  // Boat departure for a voted-off islander (cause === "voteOff"): no death
  // animation, no tombstone -- they walk to the dock, step aboard, and sail
  // off. Mirrors killEntry's guard/cleanup shape (dying set, forget(id),
  // entries.delete(id)) so update()/selectNearestClickable/syncPills all treat it the
  // same "leaving the game" way while it plays out.
  private boatDeparture(id: string, entry: Entry): void {
    this.dying.add(id);
    const s = entry.sprite;
    const pill = entry.pill;

    const board = this.dockWorld ?? this.nearestEdgePoint(s.x, s.y);
    const sailTo = this.nearestEdgePoint(board.x, board.y);

    this.ensureBoatTexture();

    const walkDist = Math.hypot(board.x - s.x, board.y - s.y);
    const walkDuration = Phaser.Math.Clamp(walkDist * 5, 400, 1400);
    if (board.x !== s.x) s.setFlipX(board.x < s.x);
    s.play("walk");

    this.tweens.add({
      targets: s,
      x: board.x,
      y: board.y,
      duration: walkDuration,
      ease: "Sine.easeInOut",
      onUpdate: () => {
        const depth = characterDepth(s.y);
        s.setDepth(depth);
        pill.setPosition(s.x, s.y - (CHAR_ORIGIN_Y * CHAR_FRAME_H + PILL_GAP));
        pill.setDepth(depth + 0.0002);
      },
      onComplete: () => this.boardAndSailOff(id, s, pill, board, sailTo),
    });
  }

  // Second half of a boat departure: the islander steps aboard (a little
  // hop), their tag pill fades out, then the boat carries them off toward the
  // water/nearest map edge, bobbing gently, until both are off-screen and get
  // cleaned up exactly like killEntry's death-tween completion does.
  private boardAndSailOff(
    id: string,
    s: Phaser.GameObjects.Sprite,
    pill: Phaser.GameObjects.Container,
    board: { x: number; y: number },
    sailTo: { x: number; y: number },
  ): void {
    if (!s.active) return; // reset already tore this down mid-tween
    s.play("idle");
    const boat = this.add.image(board.x, board.y, "boat");
    this.boats.set(id, boat);
    const facingLeft = sailTo.x < board.x;
    boat.setFlipX(facingLeft);
    s.setFlipX(facingLeft);
    const baseDepth = characterDepth(board.y);
    boat.setDepth(baseDepth - 0.0001);
    s.setDepth(baseDepth);

    // Step aboard: a small hop up onto the deck.
    this.tweens.add({
      targets: s,
      y: board.y - 4,
      duration: 220,
      yoyo: true,
      ease: "Quad.easeOut",
    });
    this.tweens.add({
      targets: pill,
      alpha: 0,
      duration: 300,
      onComplete: () => pill.destroy(),
    });

    // Sail off: drive the boat + rider by hand (a progress tween rather than
    // tweening x/y directly) so a sine bob can ride on top of the straight-
    // line path out to sea.
    const startX = board.x;
    const startY = board.y;
    const duration = Phaser.Math.Between(2500, 3500);
    // Driven by a plain { t } progress object rather than tweening s/boat's
    // x/y directly, so a sine bob can layer on top of the straight-line
    // path. The tween itself is stashed in sailTweens (keyed by id) so a
    // mid-flight reset can still find and cancel it -- killTweensOf can only
    // match by target, and progress isn't reachable from outside this scope.
    const progress = { t: 0 };
    const sailTween = this.tweens.add({
      targets: progress,
      t: 1,
      duration,
      delay: 250, // let the boarding hop read before the boat pushes off
      ease: "Sine.easeIn",
      onUpdate: () => {
        const x = Phaser.Math.Linear(startX, sailTo.x, progress.t);
        const bob = Math.sin(progress.t * Math.PI * 6) * 2;
        const y = Phaser.Math.Linear(startY, sailTo.y, progress.t) + bob;
        boat.setPosition(x, y);
        s.setPosition(x, y - 6);
        const depth = characterDepth(y);
        boat.setDepth(depth - 0.0001);
        s.setDepth(depth);
      },
      onComplete: () => {
        s.destroy();
        boat.destroy();
        this.boats.delete(id);
        this.sailTweens.delete(id);
        forget(id);
        this.entries.delete(id);
        this.dying.delete(id);
        // Plant a flag on the dock marking that this islander was voted off --
        // the boat-departure counterpart to a death tombstone.
        this.spawnDockFlag(id, board);
      },
    });
    this.sailTweens.set(id, sailTween);
  }

  // Fight-start scuffle: lunges both combatants toward each other and back a
  // couple of times, shakes them, and pops a clash spark between them. Reads
  // as a fight even though the only signal we get is the one fight:started
  // event -- combat itself runs entirely server-side.
  private playFightAnimation(aId: string, bId: string): void {
    const a = this.entries.get(aId);
    const b = this.entries.get(bId);
    if (!a || !b || this.dying.has(aId) || this.dying.has(bId)) return;

    const ax = a.sprite.x;
    const ay = a.sprite.y;
    const bx = b.sprite.x;
    const by = b.sprite.y;
    const dx = bx - ax;
    const dy = by - ay;
    const dist = Math.max(Math.hypot(dx, dy), 1);
    const nx = dx / dist;
    const ny = dy / dist;
    const lunge = Math.min(10, dist * 0.35);

    const offA = { x: 0, y: 0 };
    const offB = { x: 0, y: 0 };
    this.fightOffsets.set(aId, offA);
    this.fightOffsets.set(bId, offB);

    this.tweens.add({
      targets: offA,
      x: nx * lunge,
      y: ny * lunge - 2,
      duration: 160,
      yoyo: true,
      repeat: 2,
      ease: "Quad.easeInOut",
    });
    this.tweens.add({
      targets: offB,
      x: -nx * lunge,
      y: -ny * lunge - 2,
      duration: 160,
      yoyo: true,
      repeat: 2,
      ease: "Quad.easeInOut",
      delay: 40, // slightly out of phase so the two don't move in lockstep
    });

    // Crossed-swords clash spark at the midpoint: pops in, holds, fades.
    const midX = (ax + bx) / 2;
    const midY = (ay + by) / 2 - CHAR_ORIGIN_Y * CHAR_FRAME_H * 0.6;
    const spark = this.add.text(midX, midY, "⚔", {
      fontFamily: "monospace",
      fontSize: "16px",
      color: "#ffe14d",
    });
    spark.setOrigin(0.5, 0.5);
    spark.setDepth(VOICE_ICON_DEPTH);
    spark.setScale(0.3);
    spark.setAlpha(0);
    this.tweens.add({
      targets: spark,
      scale: { from: 0.3, to: 1.3 },
      alpha: { from: 0, to: 1 },
      duration: 180,
      ease: "Back.easeOut",
      onComplete: () => {
        this.tweens.add({
          targets: spark,
          alpha: 0,
          scale: 1.6,
          duration: 700,
          delay: 300,
          onComplete: () => spark.destroy(),
        });
      },
    });

    this.time.delayedCall(1100, () => {
      // A second fight can start before this one's cleanup fires. Only remove
      // the offsets this animation owns so an older timer cannot cancel the
      // newer scuffle halfway through.
      if (this.fightOffsets.get(aId) === offA) this.fightOffsets.delete(aId);
      if (this.fightOffsets.get(bId) === offB) this.fightOffsets.delete(bId);
    });
  }

  private flashCombatant(id: string): void {
    const entry = this.entries.get(id);
    if (!entry || this.dying.has(id)) return;
    const s = entry.sprite;
    s.setTint(0xff5a5a);
    this.tweens.add({
      targets: s,
      scaleX: { from: 1.3, to: 1 },
      scaleY: { from: 1.3, to: 1 },
      duration: 240,
      ease: "Quad.easeOut",
    });
    this.time.delayedCall(220, () => {
      if (s.active && !this.dying.has(id)) s.clearTint();
    });
  }

  // Diffs interaction nodes against the store's active conversations: spawns a
  // pulsing marker where a conversation starts, removes it when the store
  // prunes the conversation (a few seconds after it ends).
  private syncConversations(): void {
    const { conversations } = useGameStore.getState();
    for (const [id, node] of this.convNodes) {
      if (!conversations[id]) {
        node.container.destroy();
        this.convNodes.delete(id);
      }
    }
    for (const conv of Object.values(conversations)) {
      const existing = this.convNodes.get(conv.id);
      if (!existing) {
        this.convNodes.set(conv.id, this.spawnConvNode(conv.id, conv.x, conv.y, conv.outcome));
      } else if (existing.outcome !== conv.outcome) {
        // The conversation just ended (or its outcome otherwise changed) --
        // swap the marker's icon in place rather than respawning it.
        existing.outcome = conv.outcome;
        existing.icon.setText(convNodeGlyph(conv.outcome));
        // ...and, for the conversations that actually produced something, pop
        // the outcome by the pair for a beat. Deliberately transient: the spec
        // wants a cue, not a permanent badge, and most conversations end in
        // "nothing" and get no cue at all.
        if (islandFlags.outcomeIcons && isNotableOutcome(conv.outcome)) {
          // Popped over the marker's CURRENT position, not conv.x/conv.y --
          // syncConvNodePositions may have re-anchored the marker onto the
          // pair's live midpoint, and a badge at the frozen start coordinates
          // would appear detached from the pair it is describing.
          this.popOutcomeBadge(
            existing.container.x,
            existing.container.y,
            outcomePresentation(conv.outcome).icon,
          );
        }
      }
    }

    // Speech bubbles ride a participant's sprite rather than the conversation
    // itself, so they're diffed against every live conversation's participants,
    // keyed by contestant id. The value is the line to show: the newest message
    // for whoever spoke it, null (listening dots) for everyone else.
    const chat = islandFlags.calmConversations;
    const talking = new Map<string, string | null>();
    for (const conv of Object.values(conversations)) {
      // An ended conversation lingers in the store for a few seconds so the
      // marker can show its outcome. With chat bubbles on, the talk is over, so
      // the bubbles go rather than hanging a stale line over the pair; with the
      // flag off the old indicator rides until the store prunes it, as today.
      if (chat && conv.endedAt !== null) continue;
      for (const pid of conv.participantIds) {
        // A death/boat departure stops update() from driving this participant.
        // Excluding it here ensures its overhead bubble is destroyed instead
        // of freezing in place for the conversation's six-second linger.
        if (!this.entries.has(pid) || this.dying.has(pid)) continue;
        talking.set(pid, null);
      }
      if (!chat) continue;
      // Only the current speaker gets a line. Two competing text bubbles over a
      // pair is unreadable, and "who is talking right now" is the thing the
      // bubble is meant to convey.
      const last = conv.messages[conv.messages.length - 1];
      if (last && talking.has(last.speakerId)) {
        talking.set(last.speakerId, bubbleLine(last.text));
      }
    }

    for (const [id, bubble] of this.voiceIcons) {
      if (talking.has(id)) continue;
      this.voiceIcons.delete(id);
      // Fade the chat bubble out when its owner stops talking; the legacy
      // indicator vanishes instantly, exactly as it does today.
      if (bubble.chat) this.fadeOutBubble(bubble.container);
      else bubble.container.destroy();
    }
    for (const [id, line] of talking) {
      if (!this.entries.has(id)) continue;
      const existing = this.voiceIcons.get(id);
      // With the flag off `line` is always null, so this never fires and the
      // indicator is built exactly once per conversation, as today.
      if (existing && existing.line === line) continue;
      existing?.container.destroy();
      const container = chat ? this.buildSpeechBubble(line) : this.spawnVoiceIcon();
      // update() places and reveals it on the next frame; born hidden so it
      // never flashes for one frame at the map origin.
      container.setVisible(false);
      this.voiceIcons.set(id, { container, line, chat });
    }
  }

  // Fade a bubble out in place and destroy it. It has already been dropped from
  // voiceIcons by the time this runs, so update() no longer drives it -- it
  // simply dissolves where its speaker left off.
  private fadeOutBubble(container: Phaser.GameObjects.Container): void {
    this.tweens.add({
      targets: container,
      alpha: 0,
      duration: BUBBLE_FADE_MS,
      ease: "Sine.easeIn",
      onComplete: () => container.destroy(),
    });
  }

  // A brief outcome cue by a pair that just finished talking: the same flat
  // hot-pink chip language as the interaction marker, popped in over the node,
  // held, then faded. Mirrors the fight clash spark's choreography so the two
  // read as one visual family.
  private popOutcomeBadge(x: number, y: number, glyph: string): void {
    const chip = this.add.circle(0, 0, 9, CONV_NODE_COLOR, 0.95);
    const icon = this.add.text(0, 0, glyph, { fontFamily: "monospace", fontSize: "12px" });
    icon.setOrigin(0.5, 0.5);
    const badge = this.add.container(x, y - 22, [chip, icon]);
    badge.setDepth(VOICE_ICON_DEPTH);
    badge.setScale(0.3);
    badge.setAlpha(0);
    this.tweens.add({
      targets: badge,
      scale: 1,
      alpha: 1,
      y: y - 30, // drifts up as it pops, so it reads as "released" rather than parked
      duration: 220,
      ease: "Back.easeOut",
      onComplete: () => {
        this.tweens.add({
          targets: badge,
          alpha: 0,
          y: y - 38,
          duration: 520,
          delay: 900, // long enough to read, short enough not to litter the island
          onComplete: () => badge.destroy(),
        });
      },
    });
  }

  // The chat bubble: a flat white rounded rect with a hot-pink hairline border
  // and a tail, holding the spoken line -- or, before anyone has said anything,
  // the three listening dots. Anchored at the tail TIP (0, 0) and drawn upward
  // from there, which is what lets update() hang any height above the tag pill
  // without ever colliding with it.
  //
  // The art lives in an inner container so the pop-in / pulse can tween its
  // scale while update() independently drives the outer container's zoom
  // counter-scale. Tweening the two on one object would have them fight.
  private buildSpeechBubble(line: string | null): Phaser.GameObjects.Container {
    const g = this.add.graphics();
    const children: Phaser.GameObjects.GameObject[] = [g];

    let w = 15;
    let h = 10;
    let text: Phaser.GameObjects.Text | null = null;
    if (line) {
      text = this.add
        .text(0, 0, line, {
          fontFamily: "monospace",
          fontSize: "10px",
          color: BUBBLE_INK,
          resolution: 3, // authored small and counter-scaled, so oversample it
          align: "center",
          wordWrap: { width: BUBBLE_WRAP_W },
        })
        .setOrigin(0.5, 0.5);
      // Wrap first, then truncate: a long line becomes a readable three-line
      // bubble with an ellipsis rather than a tower over the island. Phaser
      // returns the already-wrapped lines, so this measures what will render.
      const lines = text.getWrappedText();
      if (lines.length > BUBBLE_MAX_LINES) {
        text.setText(`${lines.slice(0, BUBBLE_MAX_LINES).join("\n").trimEnd()}...`);
      }
      w = Math.ceil(text.width) + BUBBLE_PAD_X * 2;
      h = Math.ceil(text.height) + BUBBLE_PAD_Y * 2;
      children.push(text);
    }

    const top = -(h + BUBBLE_TAIL_H);
    g.fillStyle(BUBBLE_FILL, 0.96);
    g.lineStyle(1, CONV_NODE_COLOR, 1);
    g.fillRoundedRect(-w / 2, top, w, h, BUBBLE_RADIUS);
    g.strokeRoundedRect(-w / 2, top, w, h, BUBBLE_RADIUS);
    // Tail: filled first so it covers the body's bottom hairline, then only its
    // two slanted edges are stroked -- body and tail read as one cut shape
    // rather than a box with a triangle stuck under it.
    g.fillStyle(BUBBLE_FILL, 0.96);
    g.fillTriangle(-BUBBLE_TAIL_W / 2, -BUBBLE_TAIL_H - 1, BUBBLE_TAIL_W / 2, -BUBBLE_TAIL_H - 1, 0, 0);
    g.lineStyle(1, CONV_NODE_COLOR, 1);
    g.lineBetween(-BUBBLE_TAIL_W / 2, -BUBBLE_TAIL_H, 0, 0);
    g.lineBetween(BUBBLE_TAIL_W / 2, -BUBBLE_TAIL_H, 0, 0);

    const midY = top + h / 2;
    if (text) {
      text.setPosition(0, midY);
    } else {
      g.fillStyle(CONV_NODE_COLOR, 1);
      g.fillCircle(-4, midY, 1.1);
      g.fillCircle(0, midY, 1.1);
      g.fillCircle(4, midY, 1.1);
    }

    const inner = this.add.container(0, 0, children);
    const container = this.add.container(0, 0, [inner]);
    container.setDepth(VOICE_ICON_DEPTH);

    if (text) {
      // One-shot pop so a new line announces itself. No looping pulse here --
      // moving type is hard to read.
      this.tweens.add({
        targets: inner,
        scale: { from: 0.72, to: 1 },
        duration: 170,
        ease: "Back.easeOut",
      });
    } else {
      // Nobody has spoken yet: the dots breathe, same as the original
      // indicator, so the pair still reads as "talking".
      this.tweens.add({
        targets: inner,
        scale: { from: 0.85, to: 1.1 },
        duration: 420,
        yoyo: true,
        repeat: -1,
        ease: "Sine.easeInOut",
      });
    }
    return container;
  }

  // The pre-calmConversations indicator: a tiny speech bubble (rounded rect +
  // tail + three static dots) with no text, hot-pink on white. Kept verbatim as
  // the flag-off path so today's island is untouched; buildSpeechBubble is what
  // renders once calmConversations turns the same slot into a real chat bubble.
  // update() positions it above each conversing sprite every frame, so it's
  // created at the origin here.
  private spawnVoiceIcon(): Phaser.GameObjects.Container {
    const w = 15;
    const h = 10;
    const g = this.add.graphics();
    g.fillStyle(0xffffff, 0.95);
    g.lineStyle(1, CONV_NODE_COLOR, 1);
    g.fillRoundedRect(-w / 2, -h / 2, w, h, 3);
    g.strokeRoundedRect(-w / 2, -h / 2, w, h, 3);
    g.fillTriangle(-2, h / 2 - 1, 3, h / 2 - 1, -2, h / 2 + 3);
    g.fillStyle(CONV_NODE_COLOR, 1);
    g.fillCircle(-4, 0, 1.1);
    g.fillCircle(0, 0, 1.1);
    g.fillCircle(4, 0, 1.1);
    const container = this.add.container(0, 0, [g]);
    container.setDepth(VOICE_ICON_DEPTH);
    this.tweens.add({
      targets: g,
      scale: { from: 0.85, to: 1.1 },
      duration: 420,
      yoyo: true,
      repeat: -1,
      ease: "Sine.easeInOut",
    });
    return container;
  }

  // A soft outer halo + a solid core (tweened so it gently pulses, reading as
  // "something is happening here") with a type-specific icon on top: a
  // speech glyph while the conversation is ongoing, swapped for a handshake
  // or crossed swords once it ends (see convNodeGlyph/syncConversations).
  // Interactive for the hand cursor; the scene-level release gesture above
  // opens the transcript so a camera drag that starts here stays a drag.
  private spawnConvNode(id: string, x: number, y: number, outcome: ClientConversation["outcome"]): ConvNode {
    const halo = this.add.circle(0, 0, 10, CONV_NODE_COLOR, 0.28);
    const core = this.add.circle(0, 0, 10, CONV_NODE_COLOR, 0.95);
    const icon = this.add.text(0, 0, convNodeGlyph(outcome), {
      fontFamily: "monospace",
      fontSize: "13px",
    });
    icon.setOrigin(0.5, 0.5);
    const node = this.add.container(x, y, [halo, core, icon]);
    node.setName(id);
    node.setDepth(CONV_NODE_DEPTH);
    node.setSize(24, 24);
    node.setInteractive({ useHandCursor: true });
    this.tweens.add({
      targets: halo,
      scale: { from: 0.7, to: 1.6 },
      alpha: { from: 0.35, to: 0 },
      duration: 900,
      repeat: -1,
      ease: "Sine.easeOut",
    });
    return { container: node, icon, outcome };
  }

  // Live over-head odds tags (task 6.3): when a market's integer % changes
  // (a bet, the price heartbeat, settlement), rebuild that contestant's pill so
  // the tag tracks the live price, with green/red trend vs its seed price.
  private syncPills(): void {
    const { markets, contestants } = useGameStore.getState();
    // Recompute normalized win odds across ALL living, unsettled markets each
    // pass, so a bet on ANY market re-derives (and can flip the integer %) of
    // every other pill, not just the traded one. Same shared derivation as
    // syncRoster's spawn odds (see the note there).
    const winProbs = normalizedWinProbs(markets, contestants);
    for (const [id, entry] of this.entries) {
      if (this.dying.has(id)) continue;
      const m = markets[id];
      if (!m) continue;
      const winProb = winProbs.get(id) ?? m.priceYes;
      const pct = Math.round(winProb * 100);
      if (pct === entry.shownPct) continue;
      const trend = winProb >= (m.sparkline[0]?.[1] ?? winProb) - 1e-9 ? "up" : "down";
      const rebuilt = buildTagPill(this, { name: entry.name, odds: winProb, trend });
      rebuilt.setDepth(entry.pill.depth);
      rebuilt.setPosition(entry.pill.x, entry.pill.y);
      entry.pill.destroy();
      entry.pill = rebuilt;
      entry.shownPct = pct;
    }
  }

  private spawnSprite(contestant: PublicContestant, priceYes: number): void {
    const sprite = this.add.sprite(contestant.x, contestant.y, "contestant");
    // The contestant id rides on the GameObject name so update() can sample
    // the interpolation buffer without a parallel lookup table.
    sprite.setName(contestant.id);
    sprite.setOrigin(0.5, CHAR_ORIGIN_Y);
    sprite.setDepth(characterDepth(contestant.y));
    // Every contestant shares the same Sunnyside base look (deliberate --
    // only the tag pill differentiates them). All start on "idle", each from
    // a random frame so the roster doesn't animate in lockstep.
    const startFrame = Math.floor(Math.random() * (CHAR_ANIM.idle.end - CHAR_ANIM.idle.start + 1));
    sprite.play({ key: "idle", startFrame });
    // Hand cursor over a contestant (desktop affordance). Selection itself is
    // handled by the scene-level nearest-sprite picker (see create()), which is
    // far more forgiving for small, moving sprites -- especially at phone-fit
    // zoom where a sprite is ~10px and a pixel-exact tap almost always misses.
    sprite.setInteractive({ useHandCursor: true });

    // Live trend coloring vs 30 s ago is task 6.3; a fresh market has no
    // history to trend against, so pills start on the "up" color.
    const pill = buildTagPill(this, { name: contestant.name, odds: priceYes, trend: "up" });
    pill.setPosition(contestant.x, contestant.y - (CHAR_ORIGIN_Y * CHAR_FRAME_H + PILL_GAP));
    // Slightly above the sprite's own depth so it always draws over its own
    // body when both fall in the same y-sort band as a structure; update()
    // keeps it riding this offset every frame.
    pill.setDepth(characterDepth(contestant.y) + 0.0002);

    this.entries.set(contestant.id, {
      sprite,
      pill,
      renderX: contestant.x,
      renderY: contestant.y,
      moving: false,
      name: contestant.name,
      shownPct: Math.round(priceYes * 100),
    });
  }
}
